import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Button from "~/components/Button";
import LoadingSpinner from "~/components/LoadingSpinner";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [redisValue, setRedisValue] = useState("");
  const [mySQLValue, setMySQLValue] = useState("");
  const { data: redisData, isLoading: isRedisLoading } =
    api.example.getValue.useQuery();
  const { data: mySQLData, isLoading: isMySQLLoading } =
    api.example.getValueMySQL.useQuery();

  const apiContext = api.useContext();
  const { mutate: addValueToRedis } = api.example.addValue.useMutation({
    onSuccess: async () => {
      await apiContext.example.getValue.invalidate();
    },
  });
  const { mutate: addValueToMySQL } = api.example.addValueMySQL.useMutation({
    onSuccess: async () => {
      await apiContext.example.getValueMySQL.invalidate();
    },
  });
  return (
    <>
      <Head>
        <title>Charla Mundo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center gap-20 bg-gradient-to-b from-blueGray to-plum text-white">
        <div className="flex flex-col items-center gap-2">
          <h1>Redis</h1>
          <div className="">
            <p className="text-2xl text-white">value</p>
            {isRedisLoading ? <LoadingSpinner /> : <p>{redisData?.value}</p>}
          </div>
          <div className="">
            <p className="text-2xl text-white">Add value</p>
            <input
              className="bg-blueGray p-2"
              type="text"
              value={redisValue}
              onChange={(e) => setRedisValue(e.target.value)}
            />
            <Button onClick={() => addValueToRedis({ value: redisValue })}>
              Add Value
            </Button>
          </div>
        </div>
        <div className="flex flex-col items-center gap-2">
          <h1>mySQL</h1>
          <div className="">
            <p className="text-2xl text-white">value</p>
            {isMySQLLoading ? <LoadingSpinner /> : <p>{mySQLData?.value}</p>}
          </div>
          <div className="">
            <p className="text-2xl text-white">Add value</p>
            <input
              className="bg-blueGray p-2"
              type="text"
              value={mySQLValue}
              onChange={(e) => setMySQLValue(e.target.value)}
            />
            <Button onClick={() => addValueToMySQL({ value: mySQLValue })}>
              Add Value
            </Button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
