import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import ConvoList from "~/components/ConvoList";
import ConvoView from "~/components/ConvoView";
import LoadingSpinner from "~/components/LoadingSpinner";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const { push } = useRouter();

  useEffect(() => {
    if (!sessionData?.user) {
      void (async () => await push("/login"))();
    }
  }, [push, sessionData]);

  const { data: conversations, isLoading: conversationsLoading } =
    api.messages.getConversationsByUserId.useQuery();
  if (!conversations) return <LoadingSpinner />;
  return (
    <>
      <Head>
        <title>Charla Mundo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center gap-20 bg-gradient-to-b from-blueGray to-plum text-white">
        <div className="flex gap-12">
          {conversationsLoading ? (
            <LoadingSpinner />
          ) : (
            conversations.map((conversation) => {
              return (
                <>
                  <ConvoList />
                  <ConvoView
                    key={conversation.id}
                    conversation={conversation}
                  />
                </>
              );
            })
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
