import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Button from "~/components/Button";
import LoadingSpinner from "~/components/LoadingSpinner";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [theValue, setTheValue] = useState("");
  const { data, isLoading } = api.example.getValue.useQuery();

  const apiContext = api.useContext();
  const { mutate: addValueMutation } = api.example.addValue.useMutation({
    onSuccess: async () => {
      await apiContext.example.getValue.invalidate();
    },
  });
  return (
    <>
      <Head>
        <title>Charla Mundo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-blueGray to-plum text-white">
        <div className="flex flex-col items-center gap-2">
          <div className="">
            <p className="text-2xl text-white">value</p>
            {isLoading ? <LoadingSpinner /> : <p>{data?.value}</p>}
          </div>
          <div className="">
            <p className="text-2xl text-white">Add value</p>
            <input
              className="bg-blueGray p-2"
              type="text"
              value={theValue}
              onChange={(e) => setTheValue(e.target.value)}
            />
            <Button onClick={() => addValueMutation({ value: theValue })}>
              Add Value
            </Button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
